### ISSUE TITLE
options?. error

### ISSUE THREAD

**Issue by weilichuang** [Treverix/custom-electron-titlebar#1]
ERROR in ./node_modules/@treverix/custom-electron-titlebar/lib/titlebar.js 105:17
Module parse failed: Unexpected token (105:17)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     this._options = _objectSpread(_objectSpread({}, defaultOptions), options);
|
>     if (!options?.iconsTheme) {
|       if (_platform.isWindows || _platform.isLinux) {
|         this._options.iconsTheme = _themebar.Themebar.win;
 @ ./node_modules/@treverix/custom-electron-titlebar/lib/index.js 7:16-37
 @ ./src/Preload.ts

**Comment by Treverix** [comment]
I need some information on how to reproduce this issue and which electron version you were using when you observed the error. The custom-electron-titlebar fork is designed to work in electron 10+ applications.

**Comment by weilichuang** [comment]
Hi,I fixed it.
it is webpack problem,need babel-loader.
`module: {
        rules: [
            {
                use: {
                    loader: 'babel-loader',
                    options: {
                        presets: ['@babel/preset-env'],
                    }
                }
            }
        ],
    }`

**Comment by Treverix** [comment]
Glad to hear that! Happy hacking and have a nice day!
