### ISSUE TITLE
Cannot find module 'vs/base/common/color'.

### ISSUE THREAD

**Issue by DanielMcAssey** [Treverix/custom-electron-titlebar#11]
Got an issue with this version of custom-electron-titlebar. I think its because it changed from importing common/colour to the VSCode one?

https://github.com/Treverix/custom-electron-titlebar/blob/caa2facdb00c5936ddcbb4f8ebcce78d944eea6d/src/index.ts#L8

**Comment by Treverix** [comment]
It is probably a packaging error on my side, it should never import or require `vs/base/common/color` internally - the path mapping probably failed on that version. I check ASAP and push an update, if that's the case.

Nothing has changed with the import, it exported always the VSCode Color class of base common.

**Comment by Treverix** [comment]
The new version 4.1.6 does not show that error with the example app, at least for me.

In case that shows up with a local build, please keep in mind that we need to do `npm run build` and that a plan `tsc` is not sufficient. The project makes use of path mapping and babel is required to build the working library.
