### ISSUE TITLE
Is Work with Electron 15.0?

### ISSUE THREAD

**Issue by MoConWu** [Treverix/custom-electron-titlebar#21]
Is Work with Electron 15.0?

**Comment by Treverix** [comment]
I didn't try yet. I actually use it with electron 14. If it fails in your electron 15 environment, then report it as an issue here, I definitely plan to keep it compatible with future versions of electron.

**Comment by Lakelimbo** [comment]
> I didn't try yet. I actually use it with electron 14. If it fails in your electron 15 environment, then report it as an issue here, I definitely plan to keep it compatible with future versions of electron.

I can confirm it does not work with v15. I think it has something to do with `enableRemoteModule`.

**Comment by has-n** [comment]
I can confirm that the package works in 15.3.1.
