### ISSUE TITLE
Menu doesn't automatically close when clicking a submenu item

### ISSUE THREAD

**Issue by maierfelix** [Treverix/custom-electron-titlebar#7]
I found [this](https://github.com/AlexTorresSk/custom-electron-titlebar/issues/23#issuecomment-605416060) comment in the previous project describing the same problem.

**Desktop:**
 - OS: Windows 10
 - Electron version: 11.0.0-nightly.20200818
 - Node Version: 12.18.3

**Comment by Treverix** [comment]
Reproduceable on the latest version of the example application.

**Comment by Treverix** [comment]
Fixed with release 4.1.5. Thanks for reporting the issue!

**Comment by maierfelix** [comment]
Thanks for the quick fix!
